name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
      - uses: actions/checkout@v2
      - name: Clean install dependencies and build
        run: |
          npm ci
          npm run build
      - name: Install firebase-tools globally 🤷‍♂️
        run: npm install -g firebase-tools
      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --token $FIREBASE_TOKEN
